export const fetchStates = {
    STATEMENTS_FETCH_NOT_STARTED: 'STATEMENTS_FETCH_NOT_STARTED',
    STATEMENTS_FETCH_STATRED: 'STATEMENTS_FETCH_STATRED',
    STATEMENTS_FETCH_FAILED: 'STATEMENTS_FETCH_FAILED',
    STATEMENTS_FETCH_SUCCESS: 'STATEMENTS_FETCH_SUCCESS',

}